"""add_performance_audit_fields

Revision ID: 3aeb5e78d92b
Revises: 6e46f5564fc8
Create Date: 2026-01-27 15:47:55.199453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aeb5e78d92b'
down_revision: Union[str, Sequence[str], None] = '6e46f5564fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'latency_ms')
    # ### end Alembic commands ###
