"""add_security_audit_fields

Revision ID: 6e46f5564fc8
Revises: e5054d95f8b1
Create Date: 2026-01-27 15:32:09.710765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e46f5564fc8'
down_revision: Union[str, Sequence[str], None] = 'e5054d95f8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
