"""add_stripe_event_idempotency

Revision ID: 98fb66dce590
Revises: 3aeb5e78d92b
Create Date: 2026-01-27 16:25:32.361915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fb66dce590'
down_revision: Union[str, Sequence[str], None] = '3aeb5e78d92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_stripe_events_event_type'), 'processed_stripe_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_stripe_events_event_type'), table_name='processed_stripe_events')
    op.drop_table('processed_stripe_events')
    # ### end Alembic commands ###
