"""add_audit_fields

Revision ID: e5054d95f8b1
Revises: 373a960d6111
Create Date: 2026-01-26 18:20:19.484034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5054d95f8b1'
down_revision: Union[str, Sequence[str], None] = '373a960d6111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('payload', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit_logs', 'payload')
    op.drop_column('audit_logs', 'action')
    # ### end Alembic commands ###
