"""sync_billing_models

Revision ID: f41c8abf3f6e
Revises: 1d8528509ebe
Create Date: 2026-02-16 11:59:13.871163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41c8abf3f6e'
down_revision: Union[str, Sequence[str], None] = '1d8528509ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('vouchers', sa.Column('plan', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'plan')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
